export enum Keys {
    SET_ACCOUNT_TYPE = "SET_ACCOUNT_TYPE",
    SET_ORIGIN_AMOUNT = "SET_ORIGIN_AMOUNT",
    SET_DEPOSITING_FUNDS = "SET_DEPOSITING_FUNDS",
    SET_FORECAST_PERIOD = "SET_FORECAST_PERIOD",
}
