export enum Keys {
	INITIALIZE_BONDS = "INITIALIZE_BONDS",

	SET_INSTRUMENT_NUMBER_IN_PORTFOLIO = "SET_INSTRUMENT_NUMBER_IN_PORTFOLIO",
	REMOVE_INSTRUMENT_FROM_PORTFOLIO = "REMOVE_INSTRUMENT_FROM_PORTFOLIO",

	CHANGE_INSTRUMENT_TO_ADD_ID_INPUT = "CHANGE_INSTRUMENT_TO_ADD_ID_INPUT",
	CHANGE_INSTRUMENT_TO_ADD_NUMBER_INPUT = "CHANGE_INSTRUMENT_TO_ADD_NUMBER_INPUT",

	OPEN_ADD_INSTRUMENT_MODAL = "OPEN_ADD_INSTRUMENT_MODAL",
	CLOSE_ADD_INSTRUMENT_MODAL = "CLOSE_ADD_INSTRUMENT_MODAL"
}
