export enum Keys {
	SET_INSTRUMENT_NUMBER_IN_PORTFOLIO = "SET_INSTRUMENT_NUMBER_IN_PORTFOLIO",

	DECREMENT_INSTRUMENT_AMOUNT_IN_PORTFOLIO = "DECREMENT_INSTRUMENT_AMOUNT_IN_PORTFOLIO",
	INCREMENT_INSTRUMENT_AMOUNT_IN_PORTFOLIO = "INCREMENT_INSTRUMENT_AMOUNT_IN_PORTFOLIO"
}

